//____________________________________________________________________________
/*!

\class    genie::XyzzyInteractionListGenerator

\brief    Concrete implementations of the InteractionListGeneratorI interface.
          Generates a list of all the Interaction (= event summary) objects that
          can be generated by the Xyzzy EventGenerator.

\author   rhatcher@fnal.gov

\created  2020-02-19

\cpright  Copyright (c) 2003-2020, The GENIE Collaboration
          For the full text of the license visit http://copyright.genie-mc.org
*/
//____________________________________________________________________________

#ifndef _XYZZY_INTERACTION_GENERATOR_H_
#define _XYZZY_INTERACTION_GENERATOR_H_

#include "Framework/EventGen/InteractionListGeneratorI.h"

namespace genie {

class XyzzyInteractionListGenerator : public InteractionListGeneratorI {

public :
  XyzzyInteractionListGenerator();
  XyzzyInteractionListGenerator(string config);
 ~XyzzyInteractionListGenerator();

  // implement the InteractionListGeneratorI interface
  InteractionList * CreateInteractionList(const InitialState & init) const;

  // overload the Algorithm::Configure() methods to load private data
  // members from configuration options
  void Configure(const Registry & config);
  void Configure(string config);

private:

  void LoadConfigData(void);

  InteractionList * CreateInteractionListXyzzy     (const InitialState & init) const;

};

}      // genie namespace

#endif // _XYZZY_INTERACTION_GENERATOR_H_
